spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:authz.pub
logging:
  level:
    org.springframework.security: TRACE